### PR TITLE
feature/add_button_more_pages

### PR DESCRIPTION
**Pull request by kristysnet**
Nit: show ‘add’ button also on my task, open tasks, etc. #208

### CODE REVIEW

**Comment by phil-monroe** [comment]
nit: This isn't very DRY and could easily break if we change the way that rendering the add button works. I don't love the idea of using a before action to set an instance variable flag of whether to show the button or not, but I think that would be better than duplicating the code in every page view.

**Comment by kristysnet** [comment]
@dottorer would it be acceptable to show the add button on any page that didn't have the back button text? That would be the cleanest implementation...

**Comment by dottorer** [comment]
Yes that would be a good option, too.

**Comment by phil-monroe** [comment]
LGTM! Thanks @kristysnet !

**Pull request merged**
