### PR TITLE
Working Group Prompt is now sorted by last name alphabetically

### PR DESCRIPTION
**Pull request by NolanChan**
#435 

The working group prompt is now sorted by last name with format 'last name, first name'
The actual list of organisers isn't sorted, but that's an easy addition too if needed

### CODE REVIEW

**Comment by dottorer** [comment]
Hi @Nolanchan, looks like to new name format in the prompt broke 2 tests in CI. We would to afjust those first before the merge. I will review the fix in the review app today...thank you!

**Comment by diegoaad** [comment]
@dottorer do we always want to display "Last Name, First Name" in all languages? If in other languages makes more sense to keep showing "First Name Last Name", we could probably handle how to better display the names in the translation files. 

Depending whether we'll have the solution applying for all languages or not, we might have to think of how the ordering is impacted (not sure if it happens before or after translation). 

Also, it seems that there's a test failing because the test tries to find a person using "First Name Last Name", so we would have to update the test.

**Comment by dottorer** [comment]
@NolanChan I think we can keep it 'Lastname, Firstname' for all and just update the tests for it, we should be good to go. Works?

**Comment by diegoaad** [comment]
I believe we just need to change add_and_remove_working_group_organizers_spec.rb and add_and_remove_working_group_volunteers_spec.rb to update _roles_page.user_dropdown.select(circle_member.name)_ to use _circle_member.list_name_

**Comment by NolanChan** [comment]
Thanks for looking into it @diegoaad , I'll make the spec changes and re-upload. I'll be sure to test locally next time

**Comment by NolanChan** [comment]
I pushed up the changes to the specs, not 100% sure if they work since I'm getting weird results locally...

**Comment by dottorer** [comment]
@NolanChan @diegoaad Looks like CI is passing and I merged it in. Looks good to me and makes picking people much easier! Thanks!!!!

**Comment by phillipoertel** [comment]
Hi guys, the build broke with this change, see https://circleci.com/gh/lale-help/lale-help/543. It seems a test hasn't been adapted correctly to the changed order of first name / last name. 

Especially the feature specs are your shared safety net, so always make sure the build stays green when you push code. 

To make that easy to observe, you can install a toolbar app like [CCMenu](http://ccmenu.org/) (Mac) or [CCTray](http://cruisecontrolnet.org/projects/ccnet/wiki/CCTray_Download_Plugin) (Windows). [Here's a description](https://circleci.com/docs/polling-project-status/) how to set it up with CircleCI (it's easy).

Alternatively you can watch this icon on lale's GitHub page: https://github.com/lale-help/lale-help#lalehelp.

**Pull request merged**
