### PR TITLE
Projects now have start end date v1

### PR DESCRIPTION
**Pull request by mkristian**
this adds migration bits to calculate `start_date` and `due_date` for existing projects.

just takes over #455

### CODE REVIEW

**Comment by mkristian** [comment]
@dottorer just realized that PRs do not trigger a CI run and I just assumed everything is green on the CI side. maybe I find a way to configure it, otherwise I let you know as it would be great if contributors will get immediate feedback if they break tests ;)

**Comment by NolanChan** [comment]
Hi @mkristian, thanks for moving this over! I believe though that we'll still need to address https://github.com/lale-help/lale-help/pull/455#issuecomment-275510501 since there will be projects that don't have start/end dates

**Comment by mkristian** [comment]
@NolanChan yes, https://github.com/lale-help/lale-help/pull/464/files#diff-1eefaa69a8383df7cdf53f402273318d is hopefully addressing the existing projects and adds them. but currently I got stuck with two failing tests, where I need to understand first what exactly they are testing :)

**Comment by mkristian** [comment]
\o/ everything green again. @dottorer review deployed and ready to merge IMO

**Comment by mkristian** [comment]
merge manually - closing
@NolanChan thanks

**Pull request closed without merging**
