### PR TITLE
The Helper List can now be translated into a PDF

### PR DESCRIPTION
**Pull request by NolanChan**
Continuation of #420 

Layout has now changed to match the layout desired on issue #235 

Here's a screenshot:
screen shot 2016-10-31 at 10 51 41 pm

### CODE REVIEW

**Comment by dottorer** [comment]
Hi @NolanChan , looks like you have done more work based on the comments in #235 . The review app should deploy all pushes to the PR branch automativally, but somehow I cannot see the latest code there and cannot make it re-deploy. Did you commit your changes to the branch / PR? Just trying to wrap up the goodness and bring it all into master....

**Comment by NolanChan** [comment]
Hi @dottorer , I haven't pushed anything up yet because I'm still trying to figure out how to make the names black (according to [extra credit bullet point 1](https://github.com/lale-help/lale-help/issues/235#issuecomment-257506636)). After I figure it out I'll open up a new PR

**Comment by NolanChan** [comment]
I just updated the PR with the minor updates. Let me know if this looks good! We also need a german translation of _helperlist_. Thanks!

screen shot 2016-11-19 at 9 34 34 pm

**Comment by dottorer** [comment]
@NolanChan The German and French for the helper list are:

DE = Helferliste
FR = Liste de volontaires

Thanks!

**Comment by dottorer** [comment]
@NolanChan Looking really good, I tested in English and German. French has some missing translations which I can fix soon. I would like to merge and push out, but it says CI checks have failed. Might be temporary poltergeist issue, could we retry the CI?

Once those pass, I would deploy...

**Comment by NolanChan** [comment]
Sure, how do I rerun the circle ci tests?

**Comment by diegoaad** [comment]
I re-triggered the circle ci tests, and it seems to be passing without any issues now. I think the changes should be good to be merged.

**Pull request merged**
