### PR TITLE
feature/restyle_new_button

### PR DESCRIPTION
**Pull request by kristysnet**
Restyle 'add' button in top menu bar #102

### CODE REVIEW

**Comment by phillipoertel** [comment]
Hi Kristy, looks much better already, thanks. Here's some feedback from Ralf and me:

- could you please use a translation key instead of the text "New" directly in the template? That way we can i18n for German and French :-)
- the French word for the button is "Nouveau", IIRC. If you try that, you'll notice the button doesn't adapt it's size, and it's right-alignment to the right sidebar edge gets lost as well. Could you look into that? 
i18n is a PITA, unfortunately. From my experience, it's best to never assume that text will have an exact length in pixels.
- the plus-sign and "New" text could be a little larger/thicker. We fiddled with it and found `font-weight: semibold` for the text and `font-size: 1.2rem` for the icon looked alright.

**Comment by kristysnet** [comment]
For some reason internationalization completely slipped my mind last night. Made adjustments accordingly :)

**Comment by phillipoertel** [comment]
No worries, thanks for responding so quickly. I'll look into it tomorrow morning our time.

**Comment by phil-monroe** [comment]
LGTM

**Pull request merged**
