### PR TITLE
Admins can now generate downloadable csv file for their helperlist

### PR DESCRIPTION
**Pull request by NolanChan**
#423 

Here's version 1 of the CSV export button and functionality. Let me know how it is! 
(I had to hard code the view path in, which I really didn't like. I'm currently trying to figure out how to make it cleaner is possible)

Here are some pictures for what shows up on my end

screen shot 2016-12-01 at 12 39 05 am

screen shot 2016-12-01 at 12 40 04 am

### CODE REVIEW

**Comment by dottorer** [comment]
@NolanChan I checked out the PR in a review app. Looks great. Couple of thoughts:

* For CSV it would be better to list all fields individually:
** first_name
** last_name
** email
** language
** mobile phone
** home phone
** Street
** City
** State
** Postal
** Country
** Working Groups
** Member Since	
** Accredited until	
** Last Login	
** Help Provided	
** Last helped
 
This way the admin can sort/filter by whatever they need. Is that possible?

**Comment by NolanChan** [comment]
Hi @dottorer , I can do that. Just to confirm: for example, you want me to split up my `name` column into `first name` and `last name` for csv columns?

**Comment by dottorer** [comment]
Hi @NolanChan yes, we would split the name into 2 separate fields.

**Comment by NolanChan** [comment]
@dottorer just double checking, the list is the order that you would like the fields to show up?

**Comment by dottorer** [comment]
Yep, order looks good....

**Comment by dottorer** [comment]
@NolanChan Let me know when I can check the PR in the review app and merge it in. Would be sweet to get that all into PROD next week finally...

**Comment by dottorer** [comment]
Hey there @NolanChan Let me know when the PR is complete then I can merge and deploy :-)

**Comment by NolanChan** [comment]
Hi @dottorer , sorry for the delay. Haha, I can see that this issue is in demand :) I've been bogged down by a final project for school, I'll try my best to get something in by Wednesday night if that's ok

**Comment by dottorer** [comment]
Totally @NolanChan - much appreciated and good luck with the school project...

**Comment by NolanChan** [comment]
Hi @dottorer , I uploaded my latest version. Please let me know how it is!

screen shot 2016-12-06 at 10 49 48 pm

**Comment by dottorer** [comment]
@NolanChan This is perfect! Very helpful for the admins. I will merge and deploy. 

Only little glitch I noticed was that the label for 'Street' in the CSV is not translated to German as 'Strasse':
image

It is called 'Strasse' in the rails app so we must translate the field label, but maybe on the model we have not yet translated this one. I might check that out with @diegoaad ...

**Comment by dottorer** [comment]
Looks like in app/views/circle/members/index.csv.slim  we are using:
`header << User.human_attribute_name(:street_address_1)`
but it does not get resolved properly to 'Strasse'...

**Comment by dottorer** [comment]
@NolanChan Did some more testing after the merge into Staging. We have 2 bugs I noticed:
1. German special chars are not supported: "München" turns into "MÃ¼nchen"
2. Leading number in phone numbers are sometimes truncated: 
- "+4479696698234" turns into "4479696698234"
- "01721234567" turns into "1721234567"

image

image

Let me know if these are problematic to fix...

**Comment by NolanChan** [comment]
Hi @dottorer , the problems may be with excel and not my csv (maybe not the German translation part, but the number truncating part I believe). Could you open the csv in a notes application and let me know what the results are?

**Comment by dottorer** [comment]
Hi @nolanchan. You are right, it must be in Excel as the csv extract shows both correct umlaut values and phone numbers if opened directly. I must find out why this is happening because our users will work wirh a German Excel most likely....

**Comment by dottorer** [comment]
@phillipoertel For review of this PR, here are the open things to look into:

- German Umlaut still not shown well in XLS (but good in the csv raw)
- some phone number (long values) are shown as scientific numbers
- Header field 'Street address 1' is not translated into German
- remove URL in the Last helped field

**Pull request merged**
