### PR TITLE
Projects now have start end date 

### PR DESCRIPTION
**Pull request by NolanChan**
Validations included in #330 are implemented as well as the general date functionality:

1. Start date of the project must not in the past
2. End date of the project must be before start
3. All tasks and supplies as part of project should have a due date between start and end of project. Warn when saving task/supply.

Let me know if you have any questions!

### CODE REVIEW

**Comment by diegoaad** [comment]
Hi @NolanChan I have deployed a review app with your changes and noticed that when updating a project the start_date/due_date are not being persisted. Besides it I'm also getting an error when trying to create a brand new project with start_date/due_date. Could you please check it? I think you need to update the projects_controller to persist them.

Here's the link for the review app with your PR changes: https://lale-help-stg-pr-455.herokuapp.com (I have seeded it with a backup from lale-stg db, so there's some data in there)

**Comment by NolanChan** [comment]
Hi @diegoaad ,  I'll check on STG once I get a proper working login. From my local testing, everything seemed to show up fine for me. I'll confirm on both locations

**Comment by dottorer** [comment]
@NolanChan STG login should be fixed with pw = Lalehelp1. 

Issues in the review app were:  

[](https://rollbar.com/lale-help-stg-pr-455/lale-help-stg-pr-455/items/1/) 
[](https://rollbar.com/lale-help-stg-pr-455/lale-help-stg-pr-455/items/2/)

We are probably lacking data migrations for existing projects.

**Comment by diegoaad** [comment]
Hi @NolanChan I think the issues were gone after restarting the server. Once I deployed the review app it didn't run rake db:migrate, so I manually ran it. But I think I didn't restart the rails server after doing it, therefore it was not working as it should. After the server was restarted, everything seems to be working now.

When talking to @dottorer we thought that instead of just creating the new columns and leaving them without a value, we could re-use the start_date / due_date functions we had to update the new attributes on the migration.

**Comment by NolanChan** [comment]
Hi @diegoaad , I can uncomment the start_date and due_date functions, but will they be invoked for all the already-created projects?

**Comment by diegoaad** [comment]
@NolanChan perhaps we can leave them commented, but we need a similar function in the migration file so when migration is happening we'll set the value of the newly created column to the value returned by the function/logic.

I was thinking about something like a for each existing project call update_attributes to update start_date using the logic in the start_date function that's being commented (example in 2nd answer of stackoverflow: http://stackoverflow.com/questions/17389728/add-column-to-table-and-fix-value-for-existing-records-in-rails).

**Comment by NolanChan** [comment]
Gotcha, sounds good. I'll look into this, as I've never populated values on a migration before. Thanks for the link!

**Comment by mkristian** [comment]
closing in favor of #464 
@NolanChan please follow #464 for any updates on this PR

**Pull request closed without merging**
