### PR TITLE
Feature/edit delete comments

### PR DESCRIPTION
**Pull request by kristysnet**
Ability to edit and delete posts #80

### CODE REVIEW

**Comment by dottorer** [comment]
Nice one @kristysnet ! I will test more tomorrow, also on mobile, to see it in all forms...

**Comment by dottorer** [comment]
@kristysnet Looking good, here are a few things to fix up:

1. Actions should be shown as 'Edit'  and then 'Delete' (and be indented a few pixels to the right)
2. When it edit mode, the main action should be 'Save' not edit. The button could be styled a bit smaller as it is in a small space.
3. Seems like we are sending out a 'supply changed' email anytime someone edits a comment. I would for now not send notifications in the rare cases when someone fixes up a tipo in a comment.

Once merged, i will add translations and re-test for final pass...

**Comment by dottorer** [comment]
Other comment: I also noted that the review app for 350 did not have the usual seed data (i.e. no working group and no user 1-5). Maybe the seeds did not run through on this one...something to look for on the next rev apps...

**Comment by phillipoertel** [comment]
Yes, halfway through the seeds script was throwing an error, so only half of them were created. I fixed them yesterday & can create them in the review app 350, no big deal. 

Von unterwegs gesendet, deswegen kurz und evtl. mit Tippfehlern

**Comment by kristysnet** [comment]
@dottorer I have made adjustments per your notes. Let me know if there is anything else needed

**Comment by dottorer** [comment]
@kristysnet Looking spot on now! Well done!!!

Ready for @phillipoertel to merge in...

**Pull request merged**
