### PR TITLE
feature/comments_show_last_3

### PR DESCRIPTION
**Pull request by kristysnet**
Nit: when many comments are entered, the scrollbar is showing the oldest, not the newest #170
Only show the first 3 (latest) comments.
Added a link to show all comments

### CODE REVIEW

**Comment by phil-monroe** [comment]
@kristysnet it feels pretty weird having the comments sorted from newest to oldest... 
@dottorer is that really what we should do?

My recommendations:
1) Order comments from newest to oldest
2) Remove nested scroll frame for comments...
3) If there are more than 3 comments: only show the last three
4) Move the "show more comments" link to be centered and on top of comment discussions.

An example from Asana collapsed:
screen shot 2016-03-14 at 9 23 31 pm

and expanded:
screen shot 2016-03-14 at 9 23 38 pm

**Comment by dottorer** [comment]
@phil-monroe the Asana example looks great to me. Is it doable for us?

**Comment by kristysnet** [comment]
@phil-monroe I made those adjustments. I think it makes more sense this way.

**Comment by phil-monroe** [comment]
Looks great! Thanks @kristysnet!

**Comment by dottorer** [comment]
@kristysnet It seems we are still showing the oldest 3 comments in the collapsed form. We should show the newest, most current 3 comments and allow to expand to all comments as you have done it now. Can you take a look?

**Pull request merged**
