### PR TITLE
Task/SupplyTask Comments 

### PR DESCRIPTION
**Pull request by tmandke**
Add ability to comment on tasks and supply tasks

### CODE REVIEW

**Comment by tmandke** [comment]
@dottorer I have gone through the doc "Core functions of lale.help v1.0"

Here is my understanding and then questions related to it.
* Is there somewhere I can find visual design?
* I assume the users name will be displayed beside the comment :smile: 
  * If user is deleted they are shown as <former user>
    * will not be implementing this now but wanted to make sure I caught all my thoughts
  * If user has left the circle but not the site what do we display?
    * former user or former member or actual name ??
    * will be implementing as Actual Name in the first pass.
* Any members in a circle can comment on all tasks and supply tasks.
  * Can they comment on completed tasks/supply tasks?

**Comment by dottorer** [comment]
@tmandke Here are a few thoughts on your spec questions:
1. we can defer the 'event trail' (opened on x by Y, assigned to X on y, closed by x on Y, etc.). We should ideally track the task status changes already but not yet visualize them.
2. on user names:
- if a user leaves a group, but not the circle, no change to name display
- if a user leaves the circle, but not the site, we should behave like the user left completely.
- if a user leaves circle or site, we should display 'former user' (as translatable string....).
3.  any circle member can comments on all tasks and supplies. They can also comment on completed tasks (as one helper might close it but a second assignee might have something to add).
4. comments should appear with the latest comment in top so people can quickly see the most recent discussions. If the trail builds up, we need to find a way to scroll down or something elegant.

Let me know if any other questions or ideas come up during implementation.

**Comment by tmandke** [comment]
@phil-monroe @posixpascal I know this is a big pull request. But can you go over it. I know its a lot of code for very small thing added. Seemed like thats what I needed for it to work for both tasks and supplies.

**Comment by phil-monroe** [comment]
Code looks good to me. Pushing to staging to test it out.

**Comment by phil-monroe** [comment]
@tmandke: Code looks ok to me, but still needs styling. 

@stephanerangaya: can you come up with a UI mockup for comments on tasks / supplies?

**Comment by phil-monroe** [comment]
FYI: Reverted staging to state before comments

**Comment by posixpascal** [comment]
No problems with the code. Also we can merge #73 I'll add the rest of activeadmin later.

**Comment by dottorer** [comment]
supplies - conversation 3 of 3 2x

Styling as per mockups by Stephane. Full set of images shared on slack.

**Comment by tmandke** [comment]
looks good to me. Though this has not flipped the order of the comments. and seems like ralf wants a mini scrollable section for just comments which needs to be implemented.

**Comment by posixpascal** [comment]
Hey @tmandke, I updated the code accordingly. Only thing missing is the scrollable area. 
I'll add the rest of the features tomorrow

**Comment by dottorer** [comment]
Great stuff - thanks for all the work @posixpascal !

**Comment by dottorer** [comment]
Sensational work everyone! Looks really slick. Closing this PR and tracking upcoming bugs in #77.

**Pull request merged**
