### PR TITLE
Added FR strings

### PR DESCRIPTION
**Pull request by pierresauvignon**
Translated existing yml content to french and extended with what was in the german file.

### CODE REVIEW

**Comment by pierresauvignon** [comment]
We should be good to go for a first test on staging. No doubt that some of the wording will have to be tweaked.

**Comment by dottorer** [comment]
Thanks, Pierre, should we get all the lale-help\config\locales\views in as well? Without those the pages won't look good in French.

**Comment by pierresauvignon** [comment]
@dottorer done. 
FYI the de.yml is missing in views/circles/working_groups

**Comment by dottorer** [comment]
Thanks Pierre, i had missed that file and could add it now...

**Comment by dottorer** [comment]
@tmandke Pierre has taken a stab at the French translations. Take a lot and if it works, we can merge to see it in staging...

**Pull request merged**
