### PR TITLE
Add taskables to working group

### PR DESCRIPTION
**Pull request by jprokay**
This completes #451
Still having trouble getting rspec to run due to a NameError Exception within spec/page_objects/circle/members.rb

### CODE REVIEW

**Comment by dottorer** [comment]
@jprokay This works great in the review app. Now, we can add tasks and supplies, but I can already hear them asking about adding projects as well from such a button. Would that be a possible add on the third tab of the WG?

image

Just for completeness to offer the same options as on the top left 'add' button.

**Comment by jprokay** [comment]
Sure! I was thinking about that myself 👍

**Comment by jprokay** [comment]
@dottorer I'm going to try and get the test suite to work again this weekend. This feature is ready though

**Comment by dottorer** [comment]
@mkristian @jprokay This one is almost done. From testing in the review app:

- when on the 'Second WG' homepage and clicking 'add task', the value of the newly created task should be set to WG='Second WG' and not be changeable. We are adding only tasks to that group here. Same for supplies and projects of course.
- on the circle overview we need to decide if we should the 'add' buttons on each tab or if we show the drop down top left menu for add. It seems there both do the same.

**Comment by mkristian** [comment]
yes, this is confusing to be in the 'second WG' and click on 'add task' and then you miss the dropdownbox on workgroup and land in the 'Default WG'

but currently the `add task`, `add supply` and `add project` button just creates a task/supply/project in context of the 'current_circle' and omits the selected workgroup altogether, i.e. the button url looks like `http://localhost:3000/circles/1/tasks/new` respectively. what we actually need is something like `http://localhost:3000/circles/1/working_group/2/tasks/new` then we can pass in the select workgroup into the form. or the other way around: the task_controller does not know anything about the workgroup for which the task should be created for.

**Comment by mkristian** [comment]
closing this in favor of #465 which includes all the code from this PR. I just needed a CI run for the code changes. @jprokay please follow up on #465

**Pull request closed without merging**
