### PR TITLE
Lale-Bot comments are no longer counted in task and supply list view

### PR DESCRIPTION
**Pull request by NolanChan**
#332 

Hopefully the method name is sensibile. I chose to make the filter a scope to not clutter the view

### CODE REVIEW

**Comment by dottorer** [comment]
Hi @nolanchan. How would this manifest in the app?

**Comment by NolanChan** [comment]
@dottorer , I'm not sure I understand the question. What do you mean by "manifest" ?

**Comment by dottorer** [comment]
Sorry, just was wondering how it would look? Are we displaying something special here or just not counting the Lalebot comments in the little badge?

**Comment by NolanChan** [comment]
Hi @dottorer , everything is as it should be (Lale-bot comments are no longer counted in the comment count box). I updated the description to make it not cryptic-sounding. Sorry about the confusion

**Comment by diegoaad** [comment]
Reviewed the PR and looks good to me. @dottorer feel free to merge it.

**Pull request merged**
