### PR TITLE
Projects layout

### PR DESCRIPTION
**Pull request by jprokay**
Issue: https://github.com/lale-help/lale-help/issues/432

Changes:
- The project description now displays a table (CSS: _description_details_table) containing text description, period, and associated working group 
- Project view consists of 4 tabs: Tasks, Supplies, Comment, and Stats
- Comment consists of a comment box for leaving new comments on the project and a display of past comments which can be edited/deleted
- Stats contains Supplies, Tasks, and Volunteer stats

Remaining issues:
- Tests
- Pluralize Comment tab
- Add the description icon to the CSS
- Border in the description_details_table should not span the entire div per the mock up

### CODE REVIEW

**Comment by dottorer** [comment]
@jprokay deployed a review app under whttps://lale-help-stg-pr-444.herokuapp.com/circles/1/projects/1

Looking real good already, here are some comments:
- i think a key improvement will be the "Add task" and "Add supply" buttons that directly add new stuff to the project. Hard to do?
- when entering a new comment, focus should stay on comments tab.
- layout of description_details_table is coming together but I must make it a bit cleaner. I will send some ideas for optimal readability and use of space asap.

**Comment by dottorer** [comment]
@jprokay Some ideas on styling the details table:

- make white field stretch from left to right in light blue area as in mockup
- add rounded corners to white box
- add divider line between descr and period
- after Working Group name show " organized by " + Project organizer name as link on same line
- see if month badge will collide with white area and adjust spacing accordingly to retain visibility.

**Comment by jprokay** [comment]
I wasn't sure if you wanted all the parts of the projects layout done in one push or not (thus no buttons), but I can work on adding that in. I will get your comments implemented!

**Comment by dottorer** [comment]
I am always grateful for and excited about any contributions to the project! Thanks for your help on Lale and looking forward to the next rev :-)

**Comment by jprokay** [comment]
To clarify: the Working Group line should now have a link to the Working Group followed by text stating the project organizer?

**Comment by dottorer** [comment]
Yep, right on...

**Comment by jprokay** [comment]
I updated the code to include the following:
1) Organized by text on the Working Group line
2) Add Task button (missing translation)
3) Add Supply button (missing translation)
4) Removed borders, added lines to the table
5) Fixed routing when Editing/Deleting a comment

I was not able to figure out how to get the description details list to fill in on the left. I'm thinking it has something to do with the little calendar pill but I am not sure how to fix it. I will continue to play around with it and see if I can figure it out along with the focus on the comments tab.

**Comment by jprokay** [comment]
With some padding adjustments, I got the table in the right spot without too much extra space on top. Does it look okay or should the calendar be adjusted?
screen shot 2017-01-08 at 12 22 16 pm

**Comment by dottorer** [comment]
This looks great! I will review it in the app today, thanks a million.

**Pull request merged**
