### PR TITLE
created de.yml files for objects in locale folders.

### PR DESCRIPTION
**Pull request by dottorer**
Not sure I did this right, because I forgot to create a branch and pull
request wasn't possible later...

### CODE REVIEW

**Comment by tmandke** [comment]
I am assuming you wanted to create a bunch of commits not PRs. This can easily be done by just staging the appropriate. If you are not use to the commandline tool then you should try [source tree](https://www.sourcetreeapp.com/).

Now regarding the commit. It looks good as far as I can tell. except 1 file is missing `./config/locales//translation_de.yml`. When I get a chance I will write a quick status indicator for the locale files with en files being source of truth.

**Comment by dottorer** [comment]
The translation_de.yml file was not clear to me in terms of which strings in there require actual language translation. It looks more like a definition file than a text string file to me. Do you know what in there should be in German? Then i can take action...thanks!

**Comment by dottorer** [comment]
@tmandke Let me know what you think of the file content and if ok, let's merge. I am eager to see it on staging to try it out...

**Comment by tmandke** [comment]
@dottorer what you have done with the file is correct. The dot notation ones are just saying the translation for this attribute is the same as this other one.

example: on line 69 `location: :activerecord.models.location` means the string for `location` is same as the one for `activerecord.models.location`

**Comment by tmandke** [comment]
So this PR looks good to me

**Comment by dottorer** [comment]
Great. I think I can do the next incoming translations then. That leaves us only with a proper way to activate the locale setting, which Phil was talking about. Right now, the URL parm is lost between page transitions. I will create a new issue for you guys to hash out. Thanks!

**Comment by phil-monroe** [comment]
LGTM

**Pull request merged**
